
markdown: redcarpet
#highlighter: null
highlighter: pygments
#permalink: /:title
#categories可能是中文。那么就可能导致中文乱码的问题。所以一般去掉categories这个分类就好了
#permalink: /:categories/:year/:month/:day/:title
permalink: /:year/:month/:day/:title
staticUrl1: http://static.1.seoui.com
#关键字
kw: 个人博客，陶小松
url:
baseurl: http://blog.seoui.com
production_url: http://blog.seoui.com
exclude: [".rvmrc", ".rbenv-version", "README.md", "Rakefile", "changelog.md"]
globalTitle: 写 写我所爱&读 读我喜欢！
redcarpet:
  extensions: [strikethrough, tables]

sass:
  sass_dir: public/css
  style: :compressed

JB :
  version : 0.3.0
  comments :
    provider : duoshuo
    duoshuo :
      short_name : atpeach
    disqus :
      short_name : jekyllbootstrap
    livefyre :
      site_id : 123
    intensedebate :
      account : 123abc
    facebook :
      appid : 123
      num_posts: 5
      width: 580
      colorscheme: light